 import { provideZoneChangeDetection, importProvidersFrom, isDevMode } from "@angular/core";
import { bootstrapApplication } from '@angular/platform-browser';
import { RouteReuseStrategy, provideRouter, withPreloading, PreloadAllModules } from '@angular/router';
import { IonicRouteStrategy, provideIonicAngular } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  logOutOutline,
  logOut,
  business,
  pawOutline,
  calendar,
  barChart,
  refresh,
  hammer,
  people,
  logIn,
  personAdd,
  personCircleOutline,
  homeOutline,
  businessOutline,
  chevronForwardOutline,
  calendarOutline,
  barChartOutline,
  shieldCheckmarkOutline,
  peopleCircleOutline,
  peopleOutline,
  hammerOutline,
  medicalOutline,
  add,
  checkmarkCircleOutline,
  personCircle,
  shieldCheckmark,
  home,
  addCircle,
  checkmark,
  close,
  eye,
  eyeOff,
  lockClosed,
  mail,
  person,
  search,
  menu,
  settings,
  notifications,
  cloudUpload,
  camera,
  image,
  document,
  folder,
  trash,
  create,
  save,
  download,
  cloud,
  refresh as refreshIcon,
  sync,
  wifi,
  cellular,
  batteryFull,
  location,
  navigate,
  pin,
  call,
  chatbubble,
  heart,
  star,
  bookmark,
  share,
  informationCircle,
  helpCircle,
  warning,
  alertCircle,
  checkmarkCircle,
  closeCircle
} from 'ionicons/icons';
import { provideCharts, withDefaultRegisterables } from 'ng2-charts';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { provideServiceWorker } from '@angular/service-worker';

import { routes } from './app/app.routes';
import { AppComponent } from './app/app.component';
import { AuthInterceptor } from './app/interceptors/auth.interceptor';

addIcons({
  logOutOutline,
  logOut,
  business,
  pawOutline,
  calendar,
  barChart,
  refresh,
  hammer,
  people,
  logIn,
  personAdd,
  personCircleOutline,
  homeOutline,
  businessOutline,
  chevronForwardOutline,
  calendarOutline,
  barChartOutline,
  shieldCheckmarkOutline,
  peopleCircleOutline,
  peopleOutline,
  hammerOutline,
  medicalOutline,
  add,
  checkmarkCircleOutline,
  personCircle,
  shieldCheckmark,
  home,
  addCircle,
  checkmark,
  close,
  eye,
  eyeOff,
  lockClosed,
  mail,
  person,
  search,
  menu,
  settings,
  notifications,
  cloudUpload,
  camera,
  image,
  document,
  folder,
  trash,
  create,
  save,
  download,
  cloud,
  refreshIcon,
  sync,
  wifi,
  cellular,
  batteryFull,
  location,
  navigate,
  pin,
  call,
  chatbubble,
  heart,
  star,
  bookmark,
  share,
  informationCircle,
  helpCircle,
  warning,
  alertCircle,
  checkmarkCircle,
  closeCircle
});

bootstrapApplication(AppComponent, {
  providers: [
    provideZoneChangeDetection(), { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideIonicAngular(),
    provideRouter(routes, withPreloading(PreloadAllModules)),
    provideCharts(withDefaultRegisterables()),
    importProvidersFrom(HttpClientModule),
    { provide: HTTP_INTERCEPTORS, useClass: AuthInterceptor, multi: true },
    // Deshabilitar service worker en desarrollo para evitar problemas de cache
    ...(isDevMode() ? [] : [provideServiceWorker('ngsw-worker.js', {
      enabled: !isDevMode(),
      registrationStrategy: 'registerWhenStable:30000'
    })])
  ],
});
